Add is_clear method
petgraph/fixedbitset pull request #79
Opened 2022-07-01 10:18 UTC by nicopap

When using this library, the intent of checking if all elements in a bitset are disabled is better expressed with a specialized method. I doubt it's particularly more performant than `bitset.count_ones(..) == 0`, but when reading code using `FixedBitSet`, it's easier to understand what is going on with a `bitset.is_clear()` than a `bitset.count_ones(..) == 0`.

I also added docs so that it's less easy to get confused as to what "empty" means (I think the confusion was raised multiple times in the past)

2022-07-02 22:13 UTC, jrraymond commented
Thanks. Can you please add some tests for this function?

2022-07-02 23:02 UTC, jrraymond requested changes

2022-07-02 23:02 UTC, jrraymond commented on src/lib.rs
> +        // Note: we assume that bits outside the capacity are always disabled.
nit: I'm not sure these needs to be noted.

2022-07-03 10:16 UTC, nicopap commented
Thank for the review! Very important to keep thing names consistent in documentation. I indeed picked up "element" by just looking at the iterator methods. I'll fix that.

A question: the docs use both "enabled/disabled" and "set/unset" for value = 1/0. Any preference? I prefer "enabled/disabled" since "set" can also mean a set of values.

2022-07-03 10:20 UTC, nicopap commented on src/lib.rs
> +    /// count of enabled elements in a `FixedBitSet`.
Would "full count" work here? I feel like "count" is clearer, as it means only one thing, contrary to "number" and it also ties into the method name.

2022-07-03 10:47 UTC, nicopap commented
I'm very happy with the second pass on the docs. Although, in insight, I'm a bit skittish about both updating the doc on `is_empty` and `len` and adding `is_clear`.

2022-07-03 13:40 UTC, jrraymond commented
"enabled/disabled" is ok. Using "bit" instead of element is more important.
 
Don't worry about updating the doc on `is_empty` and `len`.

2022-07-03 13:44 UTC, jrraymond requested changes

2022-07-03 13:44 UTC, jrraymond commented on src/lib.rs
> +    /// `len` does not return the number of set bit. For that, use
`bits`

2022-07-03 13:44 UTC, jrraymond commented on src/lib.rs
> +    /// // has no bits set
☝️

2022-07-03 17:54 UTC, jrraymond requested changes
Thanks! As a final step, could you please add some test for `is_clear()`?

2022-07-03 23:19 UTC, merged

2022-07-04 07:26 UTC, nicopap commented
Thank you for the directions and the merge! Was the doc example code enough test?